### ISSUE TITLE
Bug: Newer docker version throws error when both --format and --quiet flags are set

### ISSUE THREAD

**Issue by onesien** [danmactough/jest-dynamodb-local-docker#4]
<img width="763" alt="Screenshot 2023-06-20 at 4 34 29 PM" src="https://github.com/danmactough/jest-dynamodb-local-docker/assets/484095/8416914a-3b55-46d7-916c-89c4b1bf7004">

```
node:net:1065
    throw new ERR_MISSING_ARGS(['options', 'port', 'path']);
    ^

TypeError [ERR_MISSING_ARGS]: The "options" or "port" or "path" argument must be specified
    at new NodeError (node:internal/errors:387:5)
    at Socket.connect (node:net:1065:11)
    at Timeout._onTimeout (/Users/ian.richardsonreis/Documents/Github/payments/node_modules/jest-dynamodb-local-docker/lib/globals.js:77:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'ERR_MISSING_ARGS'
}
```

```
docker ps -q --filter id=1786739c495d5ee385ab6562d3fce5a3852887ec32a8f7c74c6cc6d69deeb64f --format '{{.Ports}}'

WARNING: Ignoring custom format, because both --format and --quiet are set
```

**Comment by danmactough** [comment]
@onesien I think the error is different that what you've described

![image](https://github.com/danmactough/jest-dynamodb-local-docker/assets/357481/fa2e71c3-dd15-4aa1-a023-5fc91d7b2d8c)

I don't have this version of docker to test with. Can you figure out what changed?

**Comment by danmactough** [comment]
Ah, I see what's happening. The error is actually from the `net` library because the `port` is undefined... which must be due to some change in `docker ps` behavior. Neat.

**Comment by onesien** [comment]
ahh yeah I forgot to add the docker command

`docker ps -q --filter id=1786739c495d5ee385ab6562d3fce5a3852887ec32a8f7c74c6cc6d69deeb64f --format '{{.Ports}}'`

```
WARNING: Ignoring custom format, because both --format and --quiet are set
```

@krewllobster and I did some debugging and figured out it was the `docker ps` command

**Comment by danmactough** [comment]
Ok, it seems my local version of docker also got auto-updated, natch, so I needed to find an old version to confirm that removing the `-q` from the `docker ps` command wouldn't break anything. It won't.
