### ISSUE TITLE
Using `beforeEach` and `afterEach`

### ISSUE THREAD

**Issue by tnorlund** [danmactough/jest-dynamodb-local-docker#6]
I've recently converted my package to ES6. I was [previously running `createTable` and `deleteTable` in the `__mocks__` directory](https://github.com/tnorlund/Blog-backend/blob/main/code/nodejs/data/__mocks__/aws-sdk.js). After changing my `package.json` to be of type "module" and modifying the jest call, everything in the `__mocks__` directory is skipped. Any idea how to execute it? 

```json
{
...
  "type": "module",
  "main": "index.js",
  "jest": {
    "transform": {},
    "preset": "jest-dynamodb-local-docker"
  },
  "scripts": {
    "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js --runInBand"
  },
...
  "devDependencies": {
    "eslint": "^8.56.0",
    "jest": "^29.7.0",
    "jest-in-case": "^1.0.2",
    "jest-dynamodb-local-docker": "^2.0.2"
  },
  "dependencies": {
    "aws-sdk": "^2.1540.0"
  }
}

```

**Comment by danmactough** [comment]
Hi @tnorlund 👋🏻 

Using `__mocks__` is an interesting way to get code run at the beginning of your tests. I use the method that is documented by Jest: to specify `setupFiles` in your Jest config. I do it in my package.json:

```json
  "jest": {
    "preset": "jest-dynamodb-local-docker",
    "setupFiles": [
      "./jest-setup.js"
    ],
  }
```

You can put anything in those setup files, including your `beforeEach`/`afterEach` setup. Hope that helps!

**Comment by tnorlund** [comment]
Hi @danmactough!

You helped me out! I kept everything as is, but I added the 
```json
"setupFilesAfterEnv": ["./data/__mocks__/aws-sdk.js"]
```
value to the package.json file, and it worked!

Sounds like this approach isn't what you'd do. What would you recommend?

**Comment by danmactough** [comment]
> Sounds like this approach isn't what you'd do. What would you recommend?

That's pretty much what I was saying. The only significant difference was to rename that file. You have it in the `./data/__mocks__` directory and it's named `aws-sdk.js`. Jest expects that to mean you have a library at `./data/aws-sdk.js` that you are mocking. But that file is not mocking anything and you don't have a library at `./data/aws-sdk.js`. But the important thing is that it works! 🎉
